<?php

/**
 * @file tmdb.module
 * Contains required installation hooks.
 *
 * @todo
 * - Implement hook_help().
 */

/**
 * Implements hook_perm().
 */
function tmdb_perm() {
  return array('Administer TMDb configuration');
}

/**
 * Implements hook_menu().
 */
function tmdb_menu() {
  $items = array();
  // Configuration page:
  $items['admin/settings/tmdb'] = array(
    'title' => 'TMDb API',
    'description' => 'Configuration settings for themoviedb.org API.',
    'access arguments' => array('administer TMDb configuration'),
  );
  $items['admin/settings/tmdb/api'] = array(
    'title' => 'TMDb API',
    'description' => 'Configuration settings for themoviedb.org API.',
    'page callback' => 'tmdb_admin_api_settings',
    'access arguments' => array('administer TMDb configuration'),
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'file' => 'tmdb.admin.inc',
  );
  // API test page:
  $items['admin/settings/tmdb/test'] = array(
    'title' => 'TMDb API Test',
    'description' => 'TMDb API testing.',
    'page callback' => 'tmdb_admin_api_testing',
    'access arguments' => array('administer TMDb configuration'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'tmdb.admin.inc',
  );

  return $items;
}

/**
 * API function: TMDb API wrapper.
 */
function tmdb() {

}
